export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_SIGNOUT_SUCCESS = "USER_SIGNOUT_SUCCESS";
export const USER_AUTH_ERROR = "USER_AUTH_ERROR";
export const REMOVE_AUTH_ERROR = "REMOVE_AUTH_ERROR";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
